apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellors
  template:
    metadata:
      labels:
        app: hellors
    spec:
      containers:
        - name: helloflask
          image: symplesims/hello-python:latest
