---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellodeploy
  template:
    metadata:
      labels:
        app: hellodeploy
    spec:
      containers:
        - name: helloflask
          image: symplesims/hello-python:latest
          ports:
            - containerPort: 8050
