apiVersion: v1
kind: Pod
metadata:
  name: hellopo
  labels:
    app: hellopo
    type: demo
spec:
  containers:
    - image: symplesims/hello-python:latest
      name: hellopython
      ports:
        - containerPort: 8050
          protocol: TCP
