---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellodeploy
  template:
    metadata:
      labels:
        app: hellodeploy
    spec:
      containers:
        - name: helloflask
          image: symplesims/hello-python:latest # should be replaced with 'symplesims/hello-python:1.0'
          ports:
            - containerPort: 8050
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8050
