apiVersion: v1
kind: Pod
metadata:
  name: helloflask
  labels:
    app: helloflask
    type: demo
spec:
  containers:
    - name: helloflask
      image: symplesims/hello-python:latest
      ports:
        - containerPort: 8050
          protocol: TCP
