---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloflask-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloflask
  template:
    metadata:
      labels:
        app: helloflask
    spec:
      containers:
        - name: helloflask
          image: symplesims/helloflask:latest
          ports:
            - containerPort: 8050

---
apiVersion: v1
kind: Service
metadata:
  name: helloflask-svc
spec:
  selector:
    app: helloflask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8050
  type: LoadBalancer